config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"

  get "games" => "pages#games"

  resources :kg_games, only: [:index, :new, :create, :show, :destroy] do
    member do
      get :verify_password
      post :verify_password_check
      get :start_game
      get :end_game_screen
    end
    resources :kg_players, only: [:index, :new, :create, :destroy, :show] do
      member do
        post :kill_target
      end
    end
  end

  resources :my_games, only: [:index, :show]
  resources :dnd_spells, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dnd_spell.rb
class DndSpell < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/kg_game.rb
class KgGame < ApplicationRecord
  has_many :kg_players, dependent: :destroy
  after_initialize :set_defaults

  def check_end_of_game
    if kg_players.where(state: "alive").count <= 1
      update!(state: "finished") 
      return true
    end
    false
  end

  private

  def set_defaults
    self.state ||= "setup"
  end

end

app/models/kg_player.rb
class KgPlayer < ApplicationRecord
  belongs_to :kg_game
  belongs_to :kill_mean, optional: true
end

app/models/kill_mean.rb
class KillMean < ApplicationRecord
  has_many :kg_players
end

app/models/my_game.rb
class MyGame < ApplicationRecord
end

app/controllers/dnd_spells_controller.rb
class DndSpellsController < ApplicationController
  def index
    @dnd_spells = DndSpell.all
  end

  def show
    @dnd_spell = DndSpell.find(params[:id])
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @my_games = MyGame.all
  end

  def show
  end
end

app/controllers/kg_games_controller.rb
class KgGamesController < ApplicationController
  def index
    @kg_games = KgGame.all
  end

  def show
    @kg_game = KgGame.find(params[:id])
  end

  def new
    @kg_game = KgGame.new
  end

  def create
    @kg_game = KgGame.new(kg_game_params)
    @kg_game.state = "setup"
    @kg_game.save

    redirect_to kg_game_path(@kg_game)
  end

  def update
  end

  def edit
  end

  def destroy
    @kg_game = KgGame.find(params[:id])
    @kg_game.destroy

    redirect_to kg_games_path, status: :see_other
  end

  def verify_password
    @kg_game = KgGame.find(params[:id])
  end

  def verify_password_check
    @kg_game = KgGame.find(params[:id])
    entered_password = params[:password]

    if @kg_game.password == entered_password
      redirect_to kg_game_path(@kg_game)
    else
      flash[:alert] = "Incorrect password, try again."
      redirect_to verify_password_kg_game_path(@kg_game), alert: "Incorrect password"
    end
  end

  def start_game
    @kg_game = KgGame.find(params[:id])
    @kg_game.state = "in_progress"
    @kg_game.save

    players = @kg_game.kg_players.shuffle
    kill_means = KillMean.all.shuffle

    players.each_with_index do |player, index|
      player.update!(
        target: players[(index + 1) % players.length].id,
        kill_mean: kill_means[index]
      )
    end

    redirect_to kg_game_path(@kg_game)
  end

  def end_game_screen
  end

  private

  def kg_game_params
    params.require(:kg_game).permit(:name, :password)
  end
end

app/controllers/my_games_controller.rb
class MyGamesController < ApplicationController
  def index
    @my_games = MyGame.all
  end

  def show
    @my_game = MyGame.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def games
  end

  def killergame
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dnd_spells_helper.rb
module DndSpellsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/kg_games_helper.rb
module KgGamesHelper
end

app/helpers/kg_players_helper.rb
module KgPlayersHelper
end

app/helpers/kill_means_helper.rb
module KillMeansHelper
end

app/helpers/my_games_helper.rb
module MyGamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zorkubag</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= turbo_include_tags %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/games.html.erb
<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">Games yo</h1>

  <%= link_to kg_games_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">Killer game</p>
  <% end %>

  <%= link_to dnd_spells_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">DnD Spells</p>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">Oï bitches</h1>

  <%= link_to games_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">Games</p>
  <% end %>
</div>

app/views/pages/killergame.html.erb
<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">Welcome to Killer Game</h1>

  <%= link_to games_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">Start a game</p>
  <% end %>
</div>