config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"

  get "games" => "pages#games"

  resources :kg_games, only: [:index, :new, :create, :show, :destroy] do
    member do
      get :verify_password
      post :verify_password_check
      get :start_game
      get :end_game_screen
    end
    resources :kg_players, only: [:index, :new, :create, :destroy, :show] do
      member do
        post :kill_target
      end
    end
  end

  resources :my_games, only: [:index, :show]
  resources :dnd_spells, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dnd_spell.rb
class DndSpell < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/kg_game.rb
class KgGame < ApplicationRecord
  has_many :kg_players, dependent: :destroy
  after_initialize :set_defaults

  def check_end_of_game
    if kg_players.where(state: "alive").count <= 1
      update!(state: "finished") 
      return true
    end
    false
  end

  private

  def set_defaults
    self.state ||= "setup"
  end

end

app/models/kg_player.rb
class KgPlayer < ApplicationRecord
  belongs_to :kg_game
  belongs_to :kill_mean, optional: true
end

app/models/kill_mean.rb
class KillMean < ApplicationRecord
  has_many :kg_players
end

app/models/my_game.rb
class MyGame < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dnd_spells_controller.rb
class DndSpellsController < ApplicationController
  def index
    @dnd_spells = DndSpell.all
  end

  def show
    @dnd_spell = DndSpell.find(params[:id])
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @my_games = MyGame.all
  end

  def show
  end
end

app/controllers/kg_games_controller.rb
class KgGamesController < ApplicationController
  def index
    @kg_games = KgGame.all
  end

  def show
    @kg_game = KgGame.find(params[:id])
  end

  def new
    @kg_game = KgGame.new
  end

  def create
    @kg_game = KgGame.new(kg_game_params)
    @kg_game.state = "setup"
    @kg_game.save

    redirect_to kg_game_path(@kg_game)
  end

  def update
  end

  def edit
  end

  def destroy
    @kg_game = KgGame.find(params[:id])
    @kg_game.destroy

    redirect_to kg_games_path, status: :see_other
  end

  def verify_password
    @kg_game = KgGame.find(params[:id])
  end

  def verify_password_check
    @kg_game = KgGame.find(params[:id])
    entered_password = params[:password]

    if @kg_game.password == entered_password
      redirect_to kg_game_path(@kg_game)
    else
      flash[:alert] = "Incorrect password, try again."
      redirect_to verify_password_kg_game_path(@kg_game), alert: "Incorrect password"
    end
  end

  def start_game
    @kg_game = KgGame.find(params[:id])
    @kg_game.state = "in_progress"
    @kg_game.save

    players = @kg_game.kg_players.shuffle
    kill_means = KillMean.all.shuffle

    players.each_with_index do |player, index|
      player.update!(
        target: players[(index + 1) % players.length].id,
        kill_mean: kill_means[index]
      )
    end

    redirect_to kg_game_path(@kg_game)
  end

  def end_game_screen
  end

  private

  def kg_game_params
    params.require(:kg_game).permit(:name, :password)
  end
end

app/controllers/kg_players_controller.rb
class KgPlayersController < ApplicationController
  before_action :set_kg_game, only: [:new, :create, :destroy, :show]

  def index
  end

  def show
    @kg_game = KgGame.find(params[:kg_game_id])
    @kg_player = KgPlayer.find(params[:id])
  end

  def new
    @kg_player = KgPlayer.new
  end

  def create
    @kg_player = KgPlayer.new(kg_player_params)
    @kg_player.kg_game = @kg_game
    @kg_player.save

    redirect_to kg_game_path(@kg_game)
  end

  def destroy
    @kg_player =  @kg_game.kg_players.find(params[:id])
    @kg_player.destroy

    redirect_to kg_game_path(@kg_game), status: :see_other, notice: "Player removed!"
  end

  def update
  end

  def edit
  end

  def kill_target
    @kg_game = KgGame.find(params[:kg_game_id])
    @kg_player = KgPlayer.find(params[:id])

    victim_id = @kg_player.target.to_i # Convert to integer
    victim = KgPlayer.find_by(id: victim_id) # Use `find_by` to avoid errors if nil

    new_target_id = victim.target.to_i
    new_kill_mean = victim.kill_mean

    unless victim
      p "Error: Victim not found!"
      return redirect_to kg_game_kg_player_path(@kg_game, @kg_player)
    end

    @kg_player.update!(
      target: new_target_id,
      kill_mean: new_kill_mean#,
      #number_of_kills: @kg_player.number_of_kills + 1
    )

    victim.update!(state: "dead")

    if @kg_game.check_end_of_game
      p "Le jeu est terminé!"
      redirect_to end_game_screen_kg_game_path(@kg_game)
      return
    end

    redirect_to kg_game_kg_player_path(@kg_game, @kg_player)
  end

  private

  def kg_player_params
    params.require(:kg_player).permit(:name, :color)
  end

  def set_kg_game
    @kg_game = KgGame.find(params[:kg_game_id])
  end

end

app/controllers/kill_means_controller.rb
class KillMeansController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/my_games_controller.rb
class MyGamesController < ApplicationController
  def index
    @my_games = MyGame.all
  end

  def show
    @my_game = MyGame.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def games
  end

  def killergame
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dnd_spells_helper.rb
module DndSpellsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/kg_games_helper.rb
module KgGamesHelper
end

app/helpers/kg_players_helper.rb
module KgPlayersHelper
end

app/helpers/kill_means_helper.rb
module KillMeansHelper
end

app/helpers/my_games_helper.rb
module MyGamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dnd_spells/create.html.erb
<div>
  <h1 class="font-bold text-4xl">DndSpells#create</h1>
  <p>Find me in app/views/dnd_spells/create.html.erb</p>
</div>

app/views/dnd_spells/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">DndSpells#destroy</h1>
  <p>Find me in app/views/dnd_spells/destroy.html.erb</p>
</div>

app/views/dnd_spells/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">DndSpells#edit</h1>
  <p>Find me in app/views/dnd_spells/edit.html.erb</p>
</div>

app/views/dnd_spells/index.html.erb
<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">DnD Spells</h1>

  <div>
    <ul>
      <% @dnd_spells.each do |spell| %>
        <li><%= spell.name %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/dnd_spells/new.html.erb
<div>
  <h1 class="font-bold text-4xl">DndSpells#new</h1>
  <p>Find me in app/views/dnd_spells/new.html.erb</p>
</div>

app/views/dnd_spells/show.html.erb
<div>
  <h1 class="font-bold text-4xl">DndSpells#show</h1>
  <p>Find me in app/views/dnd_spells/show.html.erb</p>
</div>

app/views/dnd_spells/update.html.erb
<div>
  <h1 class="font-bold text-4xl">DndSpells#update</h1>
  <p>Find me in app/views/dnd_spells/update.html.erb</p>
</div>

app/views/games/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#create</h1>
  <p>Find me in app/views/games/create.html.erb</p>
</div>

app/views/games/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#destroy</h1>
  <p>Find me in app/views/games/destroy.html.erb</p>
</div>

app/views/games/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#edit</h1>
  <p>Find me in app/views/games/edit.html.erb</p>
</div>

app/views/games/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#index</h1>
  <p>Find me in app/views/games/index.html.erb</p>
</div>

app/views/games/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#new</h1>
  <p>Find me in app/views/games/new.html.erb</p>
</div>

app/views/games/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#show</h1>
  <p>Find me in app/views/games/show.html.erb</p>
</div>

app/views/games/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Games#update</h1>
  <p>Find me in app/views/games/update.html.erb</p>
</div>

app/views/kg_games/create.html.erb
<div>
  <h1 class="font-bold text-4xl">KgGames#create</h1>
  <p>Find me in app/views/kg_games/create.html.erb</p>
</div>

app/views/kg_games/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">KgGames#edit</h1>
  <p>Find me in app/views/kg_games/edit.html.erb</p>
</div>

app/views/kg_games/end_game_screen.html.erb
<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">La partie est terminée!</h1>
  

</div>

app/views/kg_games/index.html.erb
<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">Welcome to Killer Game</h1>

  <%= link_to new_kg_game_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">Create a new game</p>
  <% end %>

  <h2>Active games:</h2>

  <ul class="gap-4">
    <% @kg_games.each do |game| %>
      <li class="flex gap-4 items-center inline py-2"><%= game.name %>
        <% if game.password.present? %>
          <%= link_to verify_password_kg_game_path(game) do %>
            <span class="flex flex-row items-center gap-2 p-1 bg-[#099F55] drop-shadow-xl">Enter game</span>
          <% end %>
        <% else %>
          <%= link_to kg_game_path(game) do %>
            <span class="flex flex-row items-center gap-2 p-1 bg-[#099F55] drop-shadow-xl">Enter game</span>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/kg_games/new.html.erb
<div class="flex flex-col gap-4">
  <h1 class="font-bold text-4xl">Creating a new Killer Game party</h1>

  <%= form_with model: @kg_game do |f| %>
    <%= f.label :"Game name" %>
    <%= f.text_field :name %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.submit %>
  <% end %>

</div>

app/views/kg_games/show.html.erb
<div class="flex flex-col gap-4">
  <h1 class="font-bold text-4xl">Welcome to the Killer Game lobby</h1>
  <h2 class="text-xl font-semibold">Name of the game: <%= @kg_game.name %></h2>
  <p>Password: <%= @kg_game.password %></p>

  <h2 class="text-xl font-semibold">Players: </h2>

  <ul class="flex flex-col gap-4 border border-black p-4 ">
    <% @kg_game.kg_players.order(:name).each do |player| %>
      <li class="flex items-center gap-4">
        <%= player.name %> <%= player.color %>
        <%= link_to "Delete", kg_game_kg_player_path(@kg_game, player),
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
          class: "p-1 bg-[#9C222D] text-white" %>
        <%= link_to kg_game_kg_player_path(@kg_game, player),
          class: "p-1 bg-[#099F55] drop-shadow-xl",
          onclick: "return confirm('Are you sure you are player #{player.name}?');" do %>
          <span class="flex flex-row items-center gap-2">Enter game</span>
        <% end %>
          <% if @kg_game.state == "in_progress" %>
            <span><%= KgPlayer.find(player.target).name %></span>
            <span><%= player.kill_mean&.name %></span>
          <% end %>
      </li>
    <% end %>
  </ul>

  <% if @kg_game.state == "setup" %>
    <%= link_to new_kg_game_kg_player_path(@kg_game), class:"flex flex-row items-center gap-2 bg-[#9C1EE9] p-4 drop-shadow-xl" do %>
      <p class="text-base text-white">Add a new playa</p>
    <% end %>
  <% end%>

  <% if @kg_game.state == "setup" %>
    <%= link_to start_game_kg_game_path(@kg_game), class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
      <p class="text-base text-white">Start the game</p>
    <% end %>
  <% elsif @kg_game.state == "in_progress" %>
    <h1 class="font-bold text-4xl">Game in Progress!</h1>
  <% else %>
    <h1 class="font-bold text-4xl">Game Finished!</h1>
  <% end %>

  <%= link_to kg_games_path, class:"flex flex-row items-center gap-2 bg-[#1492CA] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">Return to Killer Game homepage</p>
  <% end %>

  <%= link_to "Delete game",
    kg_game_path(@kg_game),
    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
    class:"flex flex-row text-base text-white items-center gap-2 bg-[#9C222D] p-4 drop-shadow-xl"
  %>
</div>

app/views/kg_games/update.html.erb
<div>
  <h1 class="font-bold text-4xl">KgGames#update</h1>
  <p>Find me in app/views/kg_games/update.html.erb</p>
</div>

app/views/kg_games/verify_password.html.erb
<div class="flex flex-col gap-4">

  <% if flash[:alert] %>
    <p class="text-red-500"><%= flash[:alert] %></p>
  <% end %>

  <h1 class="font-bold text-4xl">This game is protected by a password</h1>
  <%= form_with url: verify_password_check_kg_game_path(@kg_game), method: :post do |f| %>
    <%= f.label :password, "Enter password to join" %>
    <%= f.password_field :password %>
    <%= f.submit "Verify" %>
  <% end %>

  <%= link_to kg_games_path, class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
    <svg class="w-6 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M192 0c-41.8 0-77.4 26.7-90.5 64L64 64C28.7 64 0 92.7 0 128L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-320c0-35.3-28.7-64-64-64l-37.5 0C269.4 26.7 233.8 0 192 0zm0 64a32 32 0 1 1 0 64 32 32 0 1 1 0-64zM105.8 229.3c7.9-22.3 29.1-37.3 52.8-37.3l58.3 0c34.9 0 63.1 28.3 63.1 63.1c0 22.6-12.1 43.5-31.7 54.8L216 328.4c-.2 13-10.9 23.6-24 23.6c-13.3 0-24-10.7-24-24l0-13.5c0-8.6 4.6-16.5 12.1-20.8l44.3-25.4c4.7-2.7 7.6-7.7 7.6-13.1c0-8.4-6.8-15.1-15.1-15.1l-58.3 0c-3.4 0-6.4 2.1-7.5 5.3l-.4 1.2c-4.4 12.5-18.2 19-30.6 14.6s-19-18.2-14.6-30.6l.4-1.2zM160 416a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>
    <p class="text-base text-white">Return to Killer Game homepage</p>
  <% end %>

</div>

app/views/kg_players/create.html.erb
<div>
  <h1 class="font-bold text-4xl">KgPlayers#create</h1>
  <p>Find me in app/views/kg_players/create.html.erb</p>
</div>

app/views/kg_players/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">KgPlayers#destroy</h1>
  <p>Find me in app/views/kg_players/destroy.html.erb</p>
</div>

app/views/kg_players/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">KgPlayers#edit</h1>
  <p>Find me in app/views/kg_players/edit.html.erb</p>
</div>

app/views/kg_players/index.html.erb
<div>
  <h1 class="font-bold text-4xl">KgPlayers#index</h1>
  <p>Find me in app/views/kg_players/index.html.erb</p>
</div>

app/views/kg_players/new.html.erb
<div class="flex flex-col gap-4">
  <h1 class="font-bold text-4xl">New playa</h1>

  <%= form_with model: [@kg_game, @kg_player], local: true do |f| %>
    <%= f.label :"Playa name" %>
    <%= f.text_field :name %>
    <%= f.label :"Playa color" %>
    <%= f.text_field :color %>
    <%= f.submit %>
  <% end %>
</div>

app/views/kg_players/show.html.erb
<div class="flex flex-col gap-4">
  <h1 class="font-bold text-4xl">Bienvenue <%= @kg_player.name %>!</h1>

  <% if @kg_game.state == "setup" %>
    <p class="text-base">Le jeu va bientôt commencer!</p>
  <% elsif @kg_game.state == "in_progress" %>
    <p class="text-base">La partie est en cours!</p>
  <% else %>
    <%= link_to end_game_screen_kg_game_path(@kg_game), class:"flex flex-row items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl" do %>
      <p class="text-base text-white">Le jeu est terminé! Aller à l'écran de fin de partie</p>
    <% end %>
  <% end %>

  <% if @kg_player.state == "alive" %>
    <% if @kg_game.state == "in_progress" %>
      <p class="text-base">Votre cible est: <%= KgPlayer.find(@kg_player.target).name %></p>
      <p class="text-base">Nom de la carte: <%= @kg_player.kill_mean&.name %></p>
      <p class="text-base">Zone d'action: <%= @kg_player.kill_mean&.action_zone %></p>
      <p class="text-base">Votre arme: <%= @kg_player.kill_mean&.weapon %></p>
      <p class="text-base">Ojectif: <%= @kg_player.kill_mean&.objective %></p>
      <p class="text-base"><em><%= @kg_player.kill_mean&.flavor_test %></em></p>
    <% end %>
  <% else %>
    <p class="text-base">Vous êtes mort!</p>
  <% end %>

  <% if @kg_player.state == "alive" %>
    <% if @kg_game.state == "in_progress" %>
      <%= link_to "J'ai eu ma cible!",
        kill_target_kg_game_kg_player_path(@kg_game, @kg_player),
        data: { turbo_method: :post, turbo_confirm: "!! Etes-vous certain d'avoir bien tué votre cible? (Cette action est définitive!) !!" },
        class:"flex flex-row text-base text-white items-center gap-2 bg-[#099F55] p-4 drop-shadow-xl"
      %>
    <% end %>
  <% end %>
</div>

app/views/kg_players/update.html.erb
<div>
  <h1 class="font-bold text-4xl">KgPlayers#update</h1>
  <p>Find me in app/views/kg_players/update.html.erb</p>
</div>

app/views/kill_means/create.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#create</h1>
  <p>Find me in app/views/kill_means/create.html.erb</p>
</div>

app/views/kill_means/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#destroy</h1>
  <p>Find me in app/views/kill_means/destroy.html.erb</p>
</div>

app/views/kill_means/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#edit</h1>
  <p>Find me in app/views/kill_means/edit.html.erb</p>
</div>

app/views/kill_means/index.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#index</h1>
  <p>Find me in app/views/kill_means/index.html.erb</p>
</div>

app/views/kill_means/new.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#new</h1>
  <p>Find me in app/views/kill_means/new.html.erb</p>
</div>

app/views/kill_means/show.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#show</h1>
  <p>Find me in app/views/kill_means/show.html.erb</p>
</div>

app/views/kill_means/update.html.erb
<div>
  <h1 class="font-bold text-4xl">KillMeans#update</h1>
  <p>Find me in app/views/kill_means/update.html.erb</p>
</div>

app/views/my_games/index.html.erb
<div>
  <h1 class="font-bold text-4xl">MyGames#index</h1>
  <p>Find me in app/views/my_games/index.html.erb</p>
</div>

app/views/my_games/show.html.erb
<div>
  <h1 class="font-bold text-4xl">MyGames#show</h1>
  <p>Find me in app/views/my_games/show.html.erb</p>
</div>